repos:
  - repo: local
    hooks:
    - id: mypy
      name: mypy
      entry: poetry run mypy
      language: system
      types_or: [python, pyi]
      always_run: true
      pass_filenames: true
    - id: black
      name: black
      entry: poetry run black
      language: system
      types_or: [python, pyi]
      always_run: true
      pass_filenames: true
    - id: isort
      name: isort
      entry: poetry run isort --atomic
      language: system
      always_run: true
      pass_filenames: true
    - id: autoflake
      name: autoflake
      entry: poetry run autoflake -ri --remove-all-unused-imports
      language: system
      always_run: true
      pass_filenames: true