version: "2"

services:
  py_app:
    build:
      context: sylvain_eric_python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  py_db:
    image: postgres:13.1-alpine
    container_name: py_db
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
