# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: auth.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\tmypackage\"C\n\x0cLoginRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0f\n\x07traceId\x18\x03 \x01(\t\"J\n\rLoginResponse\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0b\n\x03jwt\x18\x02 \x01(\t\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x0f\n\x07traceId\x18\x04 \x01(\t\"F\n\x0fRegisterRequest\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0f\n\x07traceId\x18\x03 \x01(\t\"@\n\x10RegisterResponse\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\x12\x0f\n\x07traceId\x18\x03 \x01(\t\"2\n\x12VerifyTokenRequest\x12\x0f\n\x07traceId\x18\x01 \x01(\t\x12\x0b\n\x03jwt\x18\x02 \x01(\t\"2\n\x13VerifyTokenResponse\x12\x0f\n\x07traceId\x18\x01 \x01(\t\x12\n\n\x02ok\x18\x02 \x01(\x08\x32\xe2\x01\n\x0b\x41uthService\x12<\n\x05Login\x12\x17.mypackage.LoginRequest\x1a\x18.mypackage.LoginResponse\"\x00\x12\x45\n\x08Register\x12\x1a.mypackage.RegisterRequest\x1a\x1b.mypackage.RegisterResponse\"\x00\x12N\n\x0bVerifyToken\x12\x1d.mypackage.VerifyTokenRequest\x1a\x1e.mypackage.VerifyTokenResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LOGINREQUEST._serialized_start=25
  _LOGINREQUEST._serialized_end=92
  _LOGINRESPONSE._serialized_start=94
  _LOGINRESPONSE._serialized_end=168
  _REGISTERREQUEST._serialized_start=170
  _REGISTERREQUEST._serialized_end=240
  _REGISTERRESPONSE._serialized_start=242
  _REGISTERRESPONSE._serialized_end=306
  _VERIFYTOKENREQUEST._serialized_start=308
  _VERIFYTOKENREQUEST._serialized_end=358
  _VERIFYTOKENRESPONSE._serialized_start=360
  _VERIFYTOKENRESPONSE._serialized_end=410
  _AUTHSERVICE._serialized_start=413
  _AUTHSERVICE._serialized_end=639
# @@protoc_insertion_point(module_scope)
